apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendfeed
  labels:
    app: udagram
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
        - name: feedapi
          image: nchandlersmith/udagram-api-feed:latest
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: udagram-api
            - secretRef:
                name: udagram-secrets
          ports:
            - containerPort: 8080
